[tox]
requires =
    tox>=4.2
env_list =
    lint
    pkg
    fedora{41}
no_package = true
skip_missing_interpreters = false

[testenv]
description = Run Tests
skip_install = true
deps =
    -r requirements/requirements.txt
pass_env =
    ANSIBLE_*
    CI
    CONTAINER_CMD
    DOCKER_*
    HOME
    IMAGE_TAG
    JUNIT_*
    MOLECULE_*
    PODMAN_*
    PYTEST_*
    REGISTRY_URL
    SSH_AUTH_SOCK
    TERM
    XDG_*
set_env =
    ANSIBLE_LOG_PATH = {env:ANSIBLE_LOG_PATH:{toxinidir}/.ansible.log/ansible.log}
    JUNIT_OUTPUT_DIR = {env:JUNIT_OUTPUT_DIR:{toxinidir}/.ansible.log}
    fedora34: IMAGE_TAG = 34
    fedora: IMAGE_TAG = rawhide
commands =
    molecule {posargs:test}

[testenv:lint]
description = Static Analysis
package = editable
deps =
    -r requirements/lint.txt
commands =
    find . -not -path './.*' -type f -name '*.py' -exec flake8 \{\} +
    find . -not -path './.*' -type f -name '*.py' -exec pylint \{\} +
    find . -not -path './.*' -type f -name '*.py' -exec bandit -c pyproject.toml \{\} +
allowlist_externals =
    find

[testenv:pkg]
description = Check Distribution Package
skip_install = true
deps =
    build
    pyroma
    readme_renderer[md]
    twine
commands_pre =
    pyproject-build --wheel --outdir dist .
commands =
    pyroma .
    twine check dist/*

[testenv:docs]
description = Build Documentation
deps =
    -r requirements/docs.txt
pass_env =
    {[testenv]setenv}
    MKDOCS_*
    SITE_URL
commands =
    mkdocs {posargs:build}

[testenv:pin]
description = Pin Dependencies
deps =
    pip-tools
commands =
    mkdir -p requirements
    pip-compile --generate-hashes --upgrade --output-file=requirements/requirements.txt pyproject.toml
    sh -c " \
      for EXTRA in docs lint; do \
      cp {toxinidir}/requirements/requirements.txt requirements/$EXTRA.txt ; \
      pip-compile --extra=$EXTRA --generate-hashes --reuse-hashes --output-file=requirements/$EXTRA.txt pyproject.toml ; \
      done \
      "
allowlist_externals =
    mkdir
    sh

[flake8]
max-line-length = 120
