galaxy_info:
  author: Carlos Meza
  description: Install Goss
  company: digitalroots
  license: Apache-2.0
  issue_tracker_url: https://github.com/drts01/ansible-collection/issues
  min_ansible_version: "2.1"
  platforms:
    - name: Ubuntu
    - name: Fedora
