---
all:
  children:
    molecule:
      hosts:
        molecule-fedora:
          ansible_connection: containers.podman.podman
          container_image: registry.fedoraproject.org/fedora:43
          # container_command: sleep 1d
          # container_privileged: false
          # container_systemd: false
          # container_tty: true
  # hosts:
  #   localhost:
  #     ansible_connection: ansible.builtin.local
