---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

ansible:
  env:
    ANSIBLE_CONFIG: ansible.cfg

scenario:
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - side_effect
    - verify
